### ISSUE TITLE
Cannot read the provided documents

### ISSUE THREAD

**Issue by odungern** [Open-MBEE/OpenSE-Cookbook#2]
Hello, 
... after 3 years I would like to renew my knowledge about OpenMBEE. However my attempt to read in the browser the documents listed under https://github.com/Open-MBEE/OpenSE-Cookbook/tree/master/Documents has failed; a Github page is opening and the content cannot be displayed. Also opening the downloaded file with Adobe Acrobat fails due to some decoding error.

**Comment by wobrschalek** [comment]
might be a browser issue.
I just downloaded and opened the pdfs fine with Chrome.

**Comment by odungern** [comment]
thanks a lot for your response. I have tried with different browsers. Was able to open it within the browser (a Github framed PDF viewer opens) with FF, Chrome and new Edge. Downloading and opening with Adobe PDF-Reader does not work; I guess some header information is wrong or missing. 
But I can now read somehow, that's most important. Thanks a lot for all your work!
